//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negocio.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negocio.net.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Confirmar.
        /// </summary>
        internal static string btnConfirmar {
            get {
                return ResourceManager.GetString("btnConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entrar.
        /// </summary>
        internal static string btnEntrar {
            get {
                return ResourceManager.GetString("btnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fechar.
        /// </summary>
        internal static string btnFechar {
            get {
                return ResourceManager.GetString("btnFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remover.
        /// </summary>
        internal static string btnRemover {
            get {
                return ResourceManager.GetString("btnRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sair.
        /// </summary>
        internal static string btnSair {
            get {
                return ResourceManager.GetString("btnSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Voltar.
        /// </summary>
        internal static string btnVoltar {
            get {
                return ResourceManager.GetString("btnVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O filtro informado se encontra incorreto..
        /// </summary>
        internal static string FiltroIncorretoDetectado {
            get {
                return ResourceManager.GetString("FiltroIncorretoDetectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando o Aplicativo.
        /// </summary>
        internal static string FrmText_Inicializacao {
            get {
                return ResourceManager.GetString("FrmText_Inicializacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso ao Aplicativo.
        /// </summary>
        internal static string FrmText_Login {
            get {
                return ResourceManager.GetString("FrmText_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma excessão nesta operação.
        /// </summary>
        internal static string FrmText_TratarExcessao {
            get {
                return ResourceManager.GetString("FrmText_TratarExcessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validações pendentes.
        /// </summary>
        internal static string FrmText_TratarValidacao {
            get {
                return ResourceManager.GetString("FrmText_TratarValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para entrar.
        /// </summary>
        internal static string HintBtnEntrar {
            get {
                return ResourceManager.GetString("HintBtnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para sair.
        /// </summary>
        internal static string HintBtnSair {
            get {
                return ResourceManager.GetString("HintBtnSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a Empresa Padrão.
        /// </summary>
        internal static string HintEmpresaAcesso {
            get {
                return ResourceManager.GetString("HintEmpresaAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nome de Usuário.
        /// </summary>
        internal static string HintNomeDeUsuario {
            get {
                return ResourceManager.GetString("HintNomeDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Senha de Acesso.
        /// </summary>
        internal static string HintSenhaDeAcesso {
            get {
                return ResourceManager.GetString("HintSenhaDeAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa padrão.
        /// </summary>
        internal static string LabelEmpresaPadrao {
            get {
                return ResourceManager.GetString("LabelEmpresaPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar aba atual.
        /// </summary>
        internal static string LabelFecharAbaAtual {
            get {
                return ResourceManager.GetString("LabelFecharAbaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar todas as abas.
        /// </summary>
        internal static string LabelFecharTodasAsAbas {
            get {
                return ResourceManager.GetString("LabelFecharTodasAsAbas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar todas as abas exceto atual.
        /// </summary>
        internal static string LabelFecharTodasAsAbasExceto {
            get {
                return ResourceManager.GetString("LabelFecharTodasAsAbasExceto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros personalizados.
        /// </summary>
        internal static string LabelFiltrosPersonalizados {
            get {
                return ResourceManager.GetString("LabelFiltrosPersonalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário.
        /// </summary>
        internal static string LabelNomeDeUsuario {
            get {
                return ResourceManager.GetString("LabelNomeDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de acesso.
        /// </summary>
        internal static string LabelSenhaDeAcesso {
            get {
                return ResourceManager.GetString("LabelSenhaDeAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar senha de acesso.
        /// </summary>
        internal static string ModuloAlterarSenhaDeAcesso {
            get {
                return ResourceManager.GetString("ModuloAlterarSenhaDeAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro Geral.
        /// </summary>
        internal static string ModuloCadastroGeral {
            get {
                return ResourceManager.GetString("ModuloCadastroGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string ModuloCidade {
            get {
                return ResourceManager.GetString("ModuloCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        internal static string ModuloClassificacao {
            get {
                return ResourceManager.GetString("ModuloClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string ModuloColaborador {
            get {
                return ResourceManager.GetString("ModuloColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string ModuloEmpresa {
            get {
                return ResourceManager.GetString("ModuloEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string ModuloEndereco {
            get {
                return ResourceManager.GetString("ModuloEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string ModuloEstado {
            get {
                return ResourceManager.GetString("ModuloEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string ModuloGrupo {
            get {
                return ResourceManager.GetString("ModuloGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string ModuloLocal {
            get {
                return ResourceManager.GetString("ModuloLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string ModuloMarca {
            get {
                return ResourceManager.GetString("ModuloMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string ModuloModelo {
            get {
                return ResourceManager.GetString("ModuloModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string ModuloPais {
            get {
                return ResourceManager.GetString("ModuloPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string ModuloProduto {
            get {
                return ResourceManager.GetString("ModuloProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        internal static string ModuloRegiao {
            get {
                return ResourceManager.GetString("ModuloRegiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair do aplicativo.
        /// </summary>
        internal static string ModuloSairDoAplicativo {
            get {
                return ResourceManager.GetString("ModuloSairDoAplicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgrupo.
        /// </summary>
        internal static string ModuloSubgrupo {
            get {
                return ResourceManager.GetString("ModuloSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cadastro.
        /// </summary>
        internal static string ModuloTipoDeCadastro {
            get {
                return ResourceManager.GetString("ModuloTipoDeCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar de Usuário.
        /// </summary>
        internal static string ModuloTrocarDeUsuario {
            get {
                return ResourceManager.GetString("ModuloTrocarDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        internal static string ModuloUnidade {
            get {
                return ResourceManager.GetString("ModuloUnidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string ModuloUsuario {
            get {
                return ResourceManager.GetString("ModuloUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando a alocação de recuros básicos.
        /// </summary>
        internal static string MsgAlocandoRecurosBasicos {
            get {
                return ResourceManager.GetString("MsgAlocandoRecurosBasicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultando disponibilidade de dados.
        /// </summary>
        internal static string MsgConsultandoDisponibilidade {
            get {
                return ResourceManager.GetString("MsgConsultandoDisponibilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa selecionada não esta acessível. Contate o Administrador.
        /// </summary>
        internal static string MsgEmpresaSemAcesso {
            get {
                return ResourceManager.GetString("MsgEmpresaSemAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro vinculado a outro registro portando não poderá ser removido..
        /// </summary>
        internal static string MsgErrorForeignKey {
            get {
                return ResourceManager.GetString("MsgErrorForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Registro possui uma coluna definida como não nula porem se encontra inconsistente..
        /// </summary>
        internal static string MsgErrorNotNull {
            get {
                return ResourceManager.GetString("MsgErrorNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você Gostaria de Finalizar Agora?.
        /// </summary>
        internal static string MsgFinalizarAplicativo {
            get {
                return ResourceManager.GetString("MsgFinalizarAplicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostaria de Remover?.
        /// </summary>
        internal static string MsgGostariaDeRemover {
            get {
                return ResourceManager.GetString("MsgGostariaDeRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando.
        /// </summary>
        internal static string MsgInicializando {
            get {
                return ResourceManager.GetString("MsgInicializando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando mecanismo com banco de dados.
        /// </summary>
        internal static string MsgInicializandoBancoDeDados {
            get {
                return ResourceManager.GetString("MsgInicializandoBancoDeDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando formulário de acesso.
        /// </summary>
        internal static string MsgInicializandoFrmLogin {
            get {
                return ResourceManager.GetString("MsgInicializandoFrmLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando formulário principal.
        /// </summary>
        internal static string MsgInicializandoFrmPrincipal {
            get {
                return ResourceManager.GetString("MsgInicializandoFrmPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este módulo não se encontra disponível.
        /// </summary>
        internal static string MsgModuloBloqueado {
            get {
                return ResourceManager.GetString("MsgModuloBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário selecionar a empresa.
        /// </summary>
        internal static string MsgNecessarioEmpresaUsuario {
            get {
                return ResourceManager.GetString("MsgNecessarioEmpresaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário informar o nome de usuário.
        /// </summary>
        internal static string MsgNecessarioNomeUsuario {
            get {
                return ResourceManager.GetString("MsgNecessarioNomeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário selecionar um registro para executar esta ação.
        /// </summary>
        internal static string MsgNecessarioSelecionarRegistro {
            get {
                return ResourceManager.GetString("MsgNecessarioSelecionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário informar o senha de acesso.
        /// </summary>
        internal static string MsgNecessarioSenhaUsuario {
            get {
                return ResourceManager.GetString("MsgNecessarioSenhaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Inativo. Contate o Administrador do Sistema.
        /// </summary>
        internal static string MsgUsuarioInativo {
            get {
                return ResourceManager.GetString("MsgUsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário ou Senha Incorretos.
        /// </summary>
        internal static string MsgUsuarioSenhaInvalido {
            get {
                return ResourceManager.GetString("MsgUsuarioSenhaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando estação de trabalho.
        /// </summary>
        internal static string MsgValidandoInstalacao {
            get {
                return ResourceManager.GetString("MsgValidandoInstalacao", resourceCulture);
            }
        }
    }
}
